# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphdef/graphdef.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from graphdef import function_pb2 as graphdef_dot_function__pb2
from graphdef import node_def_pb2 as graphdef_dot_node__def__pb2
from graphdef import versions_pb2 as graphdef_dot_versions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14graphdef/graphdef.proto\x12\x0funi_model_proto\x1a\x17graphdef/function.proto\x1a\x17graphdef/node_def.proto\x1a\x17graphdef/versions.proto\"\xac\x01\n\x08GraphDef\x12&\n\x04node\x18\x01 \x03(\x0b\x32\x18.uni_model_proto.NodeDef\x12-\n\x08versions\x18\x04 \x01(\x0b\x32\x1b.uni_model_proto.VersionDef\x12\x13\n\x07version\x18\x03 \x01(\x05\x42\x02\x18\x01\x12\x34\n\x07library\x18\x02 \x01(\x0b\x32#.uni_model_proto.FunctionDefLibraryBj\n\x08graphdefB\x0bGraphProtosP\x01ZLgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/graph_go_proto\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graphdef.graph_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\010graphdefB\013GraphProtosP\001ZLgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/graph_go_proto\370\001\001'
  _GRAPHDEF.fields_by_name['version']._options = None
  _GRAPHDEF.fields_by_name['version']._serialized_options = b'\030\001'
  _GRAPHDEF._serialized_start=117
  _GRAPHDEF._serialized_end=289
# @@protoc_insertion_point(module_scope)
