# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphdef/resource_handle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from graphdef import tensor_shape_pb2 as graphdef_dot_tensor__shape__pb2
from graphdef import types_pb2 as graphdef_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egraphdef/resource_handle.proto\x12\x0funi_model_proto\x1a\x1bgraphdef/tensor_shape.proto\x1a\x14graphdef/types.proto\"\xb4\x02\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\t\x12M\n\x11\x64types_and_shapes\x18\x06 \x03(\x0b\x32\x32.uni_model_proto.ResourceHandleProto.DtypeAndShape\x1ak\n\rDtypeAndShape\x12(\n\x05\x64type\x18\x01 \x01(\x0e\x32\x19.uni_model_proto.DataType\x12\x30\n\x05shape\x18\x02 \x01(\x0b\x32!.uni_model_proto.TensorShapeProtoJ\x04\x08\x07\x10\x08\x42w\n\x08graphdefB\x0eResourceHandleP\x01ZVgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/resource_handle_go_proto\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graphdef.resource_handle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\010graphdefB\016ResourceHandleP\001ZVgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/resource_handle_go_proto\370\001\001'
  _RESOURCEHANDLEPROTO._serialized_start=103
  _RESOURCEHANDLEPROTO._serialized_end=411
  _RESOURCEHANDLEPROTO_DTYPEANDSHAPE._serialized_start=298
  _RESOURCEHANDLEPROTO_DTYPEANDSHAPE._serialized_end=405
# @@protoc_insertion_point(module_scope)
