// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/full_type.proto

// Protobuf Java Version: 3.25.3
package graphdef;

/**
 * <pre>
 * Highly experimental and very likely to change.
 * This encoding uses tags instead of dedicated messages for regularity. In
 * particular the encoding imposes no restrictions on what the parameters of any
 * type should be, which in particular needs to be true for type symbols.
 * </pre>
 *
 * Protobuf type {@code uni_model_proto.FullTypeDef}
 */
public final class FullTypeDef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:uni_model_proto.FullTypeDef)
    FullTypeDefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FullTypeDef.newBuilder() to construct.
  private FullTypeDef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FullTypeDef() {
    typeId_ = 0;
    args_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FullTypeDef();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return graphdef.FullTypeProtos.internal_static_uni_model_proto_FullTypeDef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return graphdef.FullTypeProtos.internal_static_uni_model_proto_FullTypeDef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            graphdef.FullTypeDef.class, graphdef.FullTypeDef.Builder.class);
  }

  private int attrCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object attr_;
  public enum AttrCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    S(3),
    ATTR_NOT_SET(0);
    private final int value;
    private AttrCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AttrCase valueOf(int value) {
      return forNumber(value);
    }

    public static AttrCase forNumber(int value) {
      switch (value) {
        case 3: return S;
        case 0: return ATTR_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public AttrCase
  getAttrCase() {
    return AttrCase.forNumber(
        attrCase_);
  }

  public static final int TYPE_ID_FIELD_NUMBER = 1;
  private int typeId_ = 0;
  /**
   * <pre>
   * The principal type represented by this object. This may be a concrete type
   * (Tensor, Dataset) a type variable (used for dependent types) a type
   * symbol (Any, Union). See FullTypeId for details.
   * </pre>
   *
   * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
   * @return The enum numeric value on the wire for typeId.
   */
  @java.lang.Override public int getTypeIdValue() {
    return typeId_;
  }
  /**
   * <pre>
   * The principal type represented by this object. This may be a concrete type
   * (Tensor, Dataset) a type variable (used for dependent types) a type
   * symbol (Any, Union). See FullTypeId for details.
   * </pre>
   *
   * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
   * @return The typeId.
   */
  @java.lang.Override public graphdef.FullTypeId getTypeId() {
    graphdef.FullTypeId result = graphdef.FullTypeId.forNumber(typeId_);
    return result == null ? graphdef.FullTypeId.UNRECOGNIZED : result;
  }

  public static final int ARGS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<graphdef.FullTypeDef> args_;
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  @java.lang.Override
  public java.util.List<graphdef.FullTypeDef> getArgsList() {
    return args_;
  }
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends graphdef.FullTypeDefOrBuilder> 
      getArgsOrBuilderList() {
    return args_;
  }
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  @java.lang.Override
  public int getArgsCount() {
    return args_.size();
  }
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  @java.lang.Override
  public graphdef.FullTypeDef getArgs(int index) {
    return args_.get(index);
  }
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  @java.lang.Override
  public graphdef.FullTypeDefOrBuilder getArgsOrBuilder(
      int index) {
    return args_.get(index);
  }

  public static final int S_FIELD_NUMBER = 3;
  /**
   * <code>string s = 3;</code>
   * @return Whether the s field is set.
   */
  public boolean hasS() {
    return attrCase_ == 3;
  }
  /**
   * <code>string s = 3;</code>
   * @return The s.
   */
  public java.lang.String getS() {
    java.lang.Object ref = "";
    if (attrCase_ == 3) {
      ref = attr_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (attrCase_ == 3) {
        attr_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string s = 3;</code>
   * @return The bytes for s.
   */
  public com.google.protobuf.ByteString
      getSBytes() {
    java.lang.Object ref = "";
    if (attrCase_ == 3) {
      ref = attr_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (attrCase_ == 3) {
        attr_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (typeId_ != graphdef.FullTypeId.TFT_UNSET.getNumber()) {
      output.writeEnum(1, typeId_);
    }
    for (int i = 0; i < args_.size(); i++) {
      output.writeMessage(2, args_.get(i));
    }
    if (attrCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, attr_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (typeId_ != graphdef.FullTypeId.TFT_UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, typeId_);
    }
    for (int i = 0; i < args_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, args_.get(i));
    }
    if (attrCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, attr_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof graphdef.FullTypeDef)) {
      return super.equals(obj);
    }
    graphdef.FullTypeDef other = (graphdef.FullTypeDef) obj;

    if (typeId_ != other.typeId_) return false;
    if (!getArgsList()
        .equals(other.getArgsList())) return false;
    if (!getAttrCase().equals(other.getAttrCase())) return false;
    switch (attrCase_) {
      case 3:
        if (!getS()
            .equals(other.getS())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + typeId_;
    if (getArgsCount() > 0) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgsList().hashCode();
    }
    switch (attrCase_) {
      case 3:
        hash = (37 * hash) + S_FIELD_NUMBER;
        hash = (53 * hash) + getS().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static graphdef.FullTypeDef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.FullTypeDef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.FullTypeDef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.FullTypeDef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.FullTypeDef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.FullTypeDef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.FullTypeDef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static graphdef.FullTypeDef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static graphdef.FullTypeDef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static graphdef.FullTypeDef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static graphdef.FullTypeDef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static graphdef.FullTypeDef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(graphdef.FullTypeDef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Highly experimental and very likely to change.
   * This encoding uses tags instead of dedicated messages for regularity. In
   * particular the encoding imposes no restrictions on what the parameters of any
   * type should be, which in particular needs to be true for type symbols.
   * </pre>
   *
   * Protobuf type {@code uni_model_proto.FullTypeDef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:uni_model_proto.FullTypeDef)
      graphdef.FullTypeDefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return graphdef.FullTypeProtos.internal_static_uni_model_proto_FullTypeDef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return graphdef.FullTypeProtos.internal_static_uni_model_proto_FullTypeDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              graphdef.FullTypeDef.class, graphdef.FullTypeDef.Builder.class);
    }

    // Construct using graphdef.FullTypeDef.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      typeId_ = 0;
      if (argsBuilder_ == null) {
        args_ = java.util.Collections.emptyList();
      } else {
        args_ = null;
        argsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      attrCase_ = 0;
      attr_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return graphdef.FullTypeProtos.internal_static_uni_model_proto_FullTypeDef_descriptor;
    }

    @java.lang.Override
    public graphdef.FullTypeDef getDefaultInstanceForType() {
      return graphdef.FullTypeDef.getDefaultInstance();
    }

    @java.lang.Override
    public graphdef.FullTypeDef build() {
      graphdef.FullTypeDef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public graphdef.FullTypeDef buildPartial() {
      graphdef.FullTypeDef result = new graphdef.FullTypeDef(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(graphdef.FullTypeDef result) {
      if (argsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          args_ = java.util.Collections.unmodifiableList(args_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.args_ = args_;
      } else {
        result.args_ = argsBuilder_.build();
      }
    }

    private void buildPartial0(graphdef.FullTypeDef result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.typeId_ = typeId_;
      }
    }

    private void buildPartialOneofs(graphdef.FullTypeDef result) {
      result.attrCase_ = attrCase_;
      result.attr_ = this.attr_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof graphdef.FullTypeDef) {
        return mergeFrom((graphdef.FullTypeDef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(graphdef.FullTypeDef other) {
      if (other == graphdef.FullTypeDef.getDefaultInstance()) return this;
      if (other.typeId_ != 0) {
        setTypeIdValue(other.getTypeIdValue());
      }
      if (argsBuilder_ == null) {
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
      } else {
        if (!other.args_.isEmpty()) {
          if (argsBuilder_.isEmpty()) {
            argsBuilder_.dispose();
            argsBuilder_ = null;
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000002);
            argsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArgsFieldBuilder() : null;
          } else {
            argsBuilder_.addAllMessages(other.args_);
          }
        }
      }
      switch (other.getAttrCase()) {
        case S: {
          attrCase_ = 3;
          attr_ = other.attr_;
          onChanged();
          break;
        }
        case ATTR_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              typeId_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              graphdef.FullTypeDef m =
                  input.readMessage(
                      graphdef.FullTypeDef.parser(),
                      extensionRegistry);
              if (argsBuilder_ == null) {
                ensureArgsIsMutable();
                args_.add(m);
              } else {
                argsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              attrCase_ = 3;
              attr_ = s;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int attrCase_ = 0;
    private java.lang.Object attr_;
    public AttrCase
        getAttrCase() {
      return AttrCase.forNumber(
          attrCase_);
    }

    public Builder clearAttr() {
      attrCase_ = 0;
      attr_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int typeId_ = 0;
    /**
     * <pre>
     * The principal type represented by this object. This may be a concrete type
     * (Tensor, Dataset) a type variable (used for dependent types) a type
     * symbol (Any, Union). See FullTypeId for details.
     * </pre>
     *
     * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
     * @return The enum numeric value on the wire for typeId.
     */
    @java.lang.Override public int getTypeIdValue() {
      return typeId_;
    }
    /**
     * <pre>
     * The principal type represented by this object. This may be a concrete type
     * (Tensor, Dataset) a type variable (used for dependent types) a type
     * symbol (Any, Union). See FullTypeId for details.
     * </pre>
     *
     * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
     * @param value The enum numeric value on the wire for typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeIdValue(int value) {
      typeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The principal type represented by this object. This may be a concrete type
     * (Tensor, Dataset) a type variable (used for dependent types) a type
     * symbol (Any, Union). See FullTypeId for details.
     * </pre>
     *
     * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
     * @return The typeId.
     */
    @java.lang.Override
    public graphdef.FullTypeId getTypeId() {
      graphdef.FullTypeId result = graphdef.FullTypeId.forNumber(typeId_);
      return result == null ? graphdef.FullTypeId.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The principal type represented by this object. This may be a concrete type
     * (Tensor, Dataset) a type variable (used for dependent types) a type
     * symbol (Any, Union). See FullTypeId for details.
     * </pre>
     *
     * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
     * @param value The typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeId(graphdef.FullTypeId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      typeId_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The principal type represented by this object. This may be a concrete type
     * (Tensor, Dataset) a type variable (used for dependent types) a type
     * symbol (Any, Union). See FullTypeId for details.
     * </pre>
     *
     * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      typeId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<graphdef.FullTypeDef> args_ =
      java.util.Collections.emptyList();
    private void ensureArgsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        args_ = new java.util.ArrayList<graphdef.FullTypeDef>(args_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.FullTypeDef, graphdef.FullTypeDef.Builder, graphdef.FullTypeDefOrBuilder> argsBuilder_;

    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public java.util.List<graphdef.FullTypeDef> getArgsList() {
      if (argsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(args_);
      } else {
        return argsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public int getArgsCount() {
      if (argsBuilder_ == null) {
        return args_.size();
      } else {
        return argsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public graphdef.FullTypeDef getArgs(int index) {
      if (argsBuilder_ == null) {
        return args_.get(index);
      } else {
        return argsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder setArgs(
        int index, graphdef.FullTypeDef value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
      } else {
        argsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder setArgs(
        int index, graphdef.FullTypeDef.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.set(index, builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder addArgs(graphdef.FullTypeDef value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
      } else {
        argsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder addArgs(
        int index, graphdef.FullTypeDef value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.add(index, value);
        onChanged();
      } else {
        argsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder addArgs(
        graphdef.FullTypeDef.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.add(builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder addArgs(
        int index, graphdef.FullTypeDef.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.add(index, builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder addAllArgs(
        java.lang.Iterable<? extends graphdef.FullTypeDef> values) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
      } else {
        argsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder clearArgs() {
      if (argsBuilder_ == null) {
        args_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        argsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public Builder removeArgs(int index) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.remove(index);
        onChanged();
      } else {
        argsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public graphdef.FullTypeDef.Builder getArgsBuilder(
        int index) {
      return getArgsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public graphdef.FullTypeDefOrBuilder getArgsOrBuilder(
        int index) {
      if (argsBuilder_ == null) {
        return args_.get(index);  } else {
        return argsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public java.util.List<? extends graphdef.FullTypeDefOrBuilder> 
         getArgsOrBuilderList() {
      if (argsBuilder_ != null) {
        return argsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(args_);
      }
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public graphdef.FullTypeDef.Builder addArgsBuilder() {
      return getArgsFieldBuilder().addBuilder(
          graphdef.FullTypeDef.getDefaultInstance());
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public graphdef.FullTypeDef.Builder addArgsBuilder(
        int index) {
      return getArgsFieldBuilder().addBuilder(
          index, graphdef.FullTypeDef.getDefaultInstance());
    }
    /**
     * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
     */
    public java.util.List<graphdef.FullTypeDef.Builder> 
         getArgsBuilderList() {
      return getArgsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.FullTypeDef, graphdef.FullTypeDef.Builder, graphdef.FullTypeDefOrBuilder> 
        getArgsFieldBuilder() {
      if (argsBuilder_ == null) {
        argsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            graphdef.FullTypeDef, graphdef.FullTypeDef.Builder, graphdef.FullTypeDefOrBuilder>(
                args_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        args_ = null;
      }
      return argsBuilder_;
    }

    /**
     * <code>string s = 3;</code>
     * @return Whether the s field is set.
     */
    @java.lang.Override
    public boolean hasS() {
      return attrCase_ == 3;
    }
    /**
     * <code>string s = 3;</code>
     * @return The s.
     */
    @java.lang.Override
    public java.lang.String getS() {
      java.lang.Object ref = "";
      if (attrCase_ == 3) {
        ref = attr_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (attrCase_ == 3) {
          attr_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string s = 3;</code>
     * @return The bytes for s.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = "";
      if (attrCase_ == 3) {
        ref = attr_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (attrCase_ == 3) {
          attr_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string s = 3;</code>
     * @param value The s to set.
     * @return This builder for chaining.
     */
    public Builder setS(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      attrCase_ = 3;
      attr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string s = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearS() {
      if (attrCase_ == 3) {
        attrCase_ = 0;
        attr_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string s = 3;</code>
     * @param value The bytes for s to set.
     * @return This builder for chaining.
     */
    public Builder setSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      attrCase_ = 3;
      attr_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:uni_model_proto.FullTypeDef)
  }

  // @@protoc_insertion_point(class_scope:uni_model_proto.FullTypeDef)
  private static final graphdef.FullTypeDef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new graphdef.FullTypeDef();
  }

  public static graphdef.FullTypeDef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FullTypeDef>
      PARSER = new com.google.protobuf.AbstractParser<FullTypeDef>() {
    @java.lang.Override
    public FullTypeDef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FullTypeDef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FullTypeDef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public graphdef.FullTypeDef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

