// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/full_type.proto

package graphdef;

public interface FullTypeDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uni_model_proto.FullTypeDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The principal type represented by this object. This may be a concrete type
   * (Tensor, Dataset) a type variable (used for dependent types) a type
   * symbol (Any, Union). See FullTypeId for details.
   * </pre>
   *
   * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
   * @return The enum numeric value on the wire for typeId.
   */
  int getTypeIdValue();
  /**
   * <pre>
   * The principal type represented by this object. This may be a concrete type
   * (Tensor, Dataset) a type variable (used for dependent types) a type
   * symbol (Any, Union). See FullTypeId for details.
   * </pre>
   *
   * <code>.uni_model_proto.FullTypeId type_id = 1;</code>
   * @return The typeId.
   */
  graphdef.FullTypeId getTypeId();

  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  java.util.List<graphdef.FullTypeDef> 
      getArgsList();
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  graphdef.FullTypeDef getArgs(int index);
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  int getArgsCount();
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  java.util.List<? extends graphdef.FullTypeDefOrBuilder> 
      getArgsOrBuilderList();
  /**
   * <code>repeated .uni_model_proto.FullTypeDef args = 2;</code>
   */
  graphdef.FullTypeDefOrBuilder getArgsOrBuilder(
      int index);

  /**
   * <code>string s = 3;</code>
   * @return Whether the s field is set.
   */
  boolean hasS();
  /**
   * <code>string s = 3;</code>
   * @return The s.
   */
  java.lang.String getS();
  /**
   * <code>string s = 3;</code>
   * @return The bytes for s.
   */
  com.google.protobuf.ByteString
      getSBytes();

  public graphdef.FullTypeDef.AttrCase getAttrCase();
}
