// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/function.proto

package graphdef;

public final class FunctionProtos {
  private FunctionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDefLibrary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDefLibrary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDef_AttrEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDef_AttrEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDef_ArgAttrs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDef_ArgAttrs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDef_ArgAttrs_AttrEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDef_ArgAttrs_AttrEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDef_ArgAttrEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDef_ArgAttrEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDef_ResourceArgUniqueIdEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDef_ResourceArgUniqueIdEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDef_RetEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDef_RetEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_FunctionDef_ControlRetEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_FunctionDef_ControlRetEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_GradientDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_GradientDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_RegisteredGradient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_RegisteredGradient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027graphdef/function.proto\022\017uni_model_pro" +
      "to\032\031graphdef/attr_value.proto\032\027graphdef/" +
      "node_def.proto\032\025graphdef/op_def.proto\"\267\001" +
      "\n\022FunctionDefLibrary\022.\n\010function\030\001 \003(\0132\034" +
      ".uni_model_proto.FunctionDef\022.\n\010gradient" +
      "\030\002 \003(\0132\034.uni_model_proto.GradientDef\022A\n\024" +
      "registered_gradients\030\003 \003(\0132#.uni_model_p" +
      "roto.RegisteredGradient\"\373\006\n\013FunctionDef\022" +
      ")\n\tsignature\030\001 \001(\0132\026.uni_model_proto.OpD" +
      "ef\0224\n\004attr\030\005 \003(\0132&.uni_model_proto.Funct" +
      "ionDef.AttrEntry\022;\n\010arg_attr\030\007 \003(\0132).uni" +
      "_model_proto.FunctionDef.ArgAttrEntry\022U\n" +
      "\026resource_arg_unique_id\030\010 \003(\01325.uni_mode" +
      "l_proto.FunctionDef.ResourceArgUniqueIdE" +
      "ntry\022*\n\010node_def\030\003 \003(\0132\030.uni_model_proto" +
      ".NodeDef\0222\n\003ret\030\004 \003(\0132%.uni_model_proto." +
      "FunctionDef.RetEntry\022A\n\013control_ret\030\006 \003(" +
      "\0132,.uni_model_proto.FunctionDef.ControlR" +
      "etEntry\032G\n\tAttrEntry\022\013\n\003key\030\001 \001(\t\022)\n\005val" +
      "ue\030\002 \001(\0132\032.uni_model_proto.AttrValue:\0028\001" +
      "\032\222\001\n\010ArgAttrs\022=\n\004attr\030\001 \003(\0132/.uni_model_" +
      "proto.FunctionDef.ArgAttrs.AttrEntry\032G\n\t" +
      "AttrEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032." +
      "uni_model_proto.AttrValue:\0028\001\032U\n\014ArgAttr" +
      "Entry\022\013\n\003key\030\001 \001(\r\0224\n\005value\030\002 \001(\0132%.uni_" +
      "model_proto.FunctionDef.ArgAttrs:\0028\001\032:\n\030" +
      "ResourceArgUniqueIdEntry\022\013\n\003key\030\001 \001(\r\022\r\n" +
      "\005value\030\002 \001(\r:\0028\001\032*\n\010RetEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\0321\n\017ControlRetEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001J\004\010\002\020\003\";\n" +
      "\013GradientDef\022\025\n\rfunction_name\030\001 \001(\t\022\025\n\rg" +
      "radient_func\030\002 \001(\t\"G\n\022RegisteredGradient" +
      "\022\025\n\rgradient_func\030\001 \001(\t\022\032\n\022registered_op" +
      "_type\030\002 \001(\tBp\n\010graphdefB\016FunctionProtosP" +
      "\001ZOgithub.com/tensorflow/tensorflow/tens" +
      "orflow/go/core/framework/function_go_pro" +
      "to\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          graphdef.AttrValueProtos.getDescriptor(),
          graphdef.NodeProto.getDescriptor(),
          graphdef.OpDefProtos.getDescriptor(),
        });
    internal_static_uni_model_proto_FunctionDefLibrary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uni_model_proto_FunctionDefLibrary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDefLibrary_descriptor,
        new java.lang.String[] { "Function", "Gradient", "RegisteredGradients", });
    internal_static_uni_model_proto_FunctionDef_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_uni_model_proto_FunctionDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDef_descriptor,
        new java.lang.String[] { "Signature", "Attr", "ArgAttr", "ResourceArgUniqueId", "NodeDef", "Ret", "ControlRet", });
    internal_static_uni_model_proto_FunctionDef_AttrEntry_descriptor =
      internal_static_uni_model_proto_FunctionDef_descriptor.getNestedTypes().get(0);
    internal_static_uni_model_proto_FunctionDef_AttrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDef_AttrEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_uni_model_proto_FunctionDef_ArgAttrs_descriptor =
      internal_static_uni_model_proto_FunctionDef_descriptor.getNestedTypes().get(1);
    internal_static_uni_model_proto_FunctionDef_ArgAttrs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDef_ArgAttrs_descriptor,
        new java.lang.String[] { "Attr", });
    internal_static_uni_model_proto_FunctionDef_ArgAttrs_AttrEntry_descriptor =
      internal_static_uni_model_proto_FunctionDef_ArgAttrs_descriptor.getNestedTypes().get(0);
    internal_static_uni_model_proto_FunctionDef_ArgAttrs_AttrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDef_ArgAttrs_AttrEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_uni_model_proto_FunctionDef_ArgAttrEntry_descriptor =
      internal_static_uni_model_proto_FunctionDef_descriptor.getNestedTypes().get(2);
    internal_static_uni_model_proto_FunctionDef_ArgAttrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDef_ArgAttrEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_uni_model_proto_FunctionDef_ResourceArgUniqueIdEntry_descriptor =
      internal_static_uni_model_proto_FunctionDef_descriptor.getNestedTypes().get(3);
    internal_static_uni_model_proto_FunctionDef_ResourceArgUniqueIdEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDef_ResourceArgUniqueIdEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_uni_model_proto_FunctionDef_RetEntry_descriptor =
      internal_static_uni_model_proto_FunctionDef_descriptor.getNestedTypes().get(4);
    internal_static_uni_model_proto_FunctionDef_RetEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDef_RetEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_uni_model_proto_FunctionDef_ControlRetEntry_descriptor =
      internal_static_uni_model_proto_FunctionDef_descriptor.getNestedTypes().get(5);
    internal_static_uni_model_proto_FunctionDef_ControlRetEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_FunctionDef_ControlRetEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_uni_model_proto_GradientDef_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_uni_model_proto_GradientDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_GradientDef_descriptor,
        new java.lang.String[] { "FunctionName", "GradientFunc", });
    internal_static_uni_model_proto_RegisteredGradient_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_uni_model_proto_RegisteredGradient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_RegisteredGradient_descriptor,
        new java.lang.String[] { "GradientFunc", "RegisteredOpType", });
    graphdef.AttrValueProtos.getDescriptor();
    graphdef.NodeProto.getDescriptor();
    graphdef.OpDefProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
