// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/function.proto

package graphdef;

/**
 * <pre>
 * A library is a set of named functions.
 * </pre>
 *
 * Protobuf type {@code uni_model_proto.FunctionDefLibrary}
 */
public final class FunctionDefLibrary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:uni_model_proto.FunctionDefLibrary)
    FunctionDefLibraryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FunctionDefLibrary.newBuilder() to construct.
  private FunctionDefLibrary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FunctionDefLibrary() {
    function_ = java.util.Collections.emptyList();
    gradient_ = java.util.Collections.emptyList();
    registeredGradients_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FunctionDefLibrary();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return graphdef.FunctionProtos.internal_static_uni_model_proto_FunctionDefLibrary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return graphdef.FunctionProtos.internal_static_uni_model_proto_FunctionDefLibrary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            graphdef.FunctionDefLibrary.class, graphdef.FunctionDefLibrary.Builder.class);
  }

  public static final int FUNCTION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<graphdef.FunctionDef> function_;
  /**
   * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
   */
  @java.lang.Override
  public java.util.List<graphdef.FunctionDef> getFunctionList() {
    return function_;
  }
  /**
   * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends graphdef.FunctionDefOrBuilder> 
      getFunctionOrBuilderList() {
    return function_;
  }
  /**
   * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
   */
  @java.lang.Override
  public int getFunctionCount() {
    return function_.size();
  }
  /**
   * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
   */
  @java.lang.Override
  public graphdef.FunctionDef getFunction(int index) {
    return function_.get(index);
  }
  /**
   * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
   */
  @java.lang.Override
  public graphdef.FunctionDefOrBuilder getFunctionOrBuilder(
      int index) {
    return function_.get(index);
  }

  public static final int GRADIENT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<graphdef.GradientDef> gradient_;
  /**
   * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
   */
  @java.lang.Override
  public java.util.List<graphdef.GradientDef> getGradientList() {
    return gradient_;
  }
  /**
   * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends graphdef.GradientDefOrBuilder> 
      getGradientOrBuilderList() {
    return gradient_;
  }
  /**
   * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
   */
  @java.lang.Override
  public int getGradientCount() {
    return gradient_.size();
  }
  /**
   * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
   */
  @java.lang.Override
  public graphdef.GradientDef getGradient(int index) {
    return gradient_.get(index);
  }
  /**
   * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
   */
  @java.lang.Override
  public graphdef.GradientDefOrBuilder getGradientOrBuilder(
      int index) {
    return gradient_.get(index);
  }

  public static final int REGISTERED_GRADIENTS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<graphdef.RegisteredGradient> registeredGradients_;
  /**
   * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
   */
  @java.lang.Override
  public java.util.List<graphdef.RegisteredGradient> getRegisteredGradientsList() {
    return registeredGradients_;
  }
  /**
   * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends graphdef.RegisteredGradientOrBuilder> 
      getRegisteredGradientsOrBuilderList() {
    return registeredGradients_;
  }
  /**
   * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
   */
  @java.lang.Override
  public int getRegisteredGradientsCount() {
    return registeredGradients_.size();
  }
  /**
   * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
   */
  @java.lang.Override
  public graphdef.RegisteredGradient getRegisteredGradients(int index) {
    return registeredGradients_.get(index);
  }
  /**
   * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
   */
  @java.lang.Override
  public graphdef.RegisteredGradientOrBuilder getRegisteredGradientsOrBuilder(
      int index) {
    return registeredGradients_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < function_.size(); i++) {
      output.writeMessage(1, function_.get(i));
    }
    for (int i = 0; i < gradient_.size(); i++) {
      output.writeMessage(2, gradient_.get(i));
    }
    for (int i = 0; i < registeredGradients_.size(); i++) {
      output.writeMessage(3, registeredGradients_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < function_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, function_.get(i));
    }
    for (int i = 0; i < gradient_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, gradient_.get(i));
    }
    for (int i = 0; i < registeredGradients_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, registeredGradients_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof graphdef.FunctionDefLibrary)) {
      return super.equals(obj);
    }
    graphdef.FunctionDefLibrary other = (graphdef.FunctionDefLibrary) obj;

    if (!getFunctionList()
        .equals(other.getFunctionList())) return false;
    if (!getGradientList()
        .equals(other.getGradientList())) return false;
    if (!getRegisteredGradientsList()
        .equals(other.getRegisteredGradientsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFunctionCount() > 0) {
      hash = (37 * hash) + FUNCTION_FIELD_NUMBER;
      hash = (53 * hash) + getFunctionList().hashCode();
    }
    if (getGradientCount() > 0) {
      hash = (37 * hash) + GRADIENT_FIELD_NUMBER;
      hash = (53 * hash) + getGradientList().hashCode();
    }
    if (getRegisteredGradientsCount() > 0) {
      hash = (37 * hash) + REGISTERED_GRADIENTS_FIELD_NUMBER;
      hash = (53 * hash) + getRegisteredGradientsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static graphdef.FunctionDefLibrary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.FunctionDefLibrary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.FunctionDefLibrary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.FunctionDefLibrary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.FunctionDefLibrary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.FunctionDefLibrary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.FunctionDefLibrary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static graphdef.FunctionDefLibrary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static graphdef.FunctionDefLibrary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static graphdef.FunctionDefLibrary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static graphdef.FunctionDefLibrary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static graphdef.FunctionDefLibrary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(graphdef.FunctionDefLibrary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A library is a set of named functions.
   * </pre>
   *
   * Protobuf type {@code uni_model_proto.FunctionDefLibrary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:uni_model_proto.FunctionDefLibrary)
      graphdef.FunctionDefLibraryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return graphdef.FunctionProtos.internal_static_uni_model_proto_FunctionDefLibrary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return graphdef.FunctionProtos.internal_static_uni_model_proto_FunctionDefLibrary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              graphdef.FunctionDefLibrary.class, graphdef.FunctionDefLibrary.Builder.class);
    }

    // Construct using graphdef.FunctionDefLibrary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (functionBuilder_ == null) {
        function_ = java.util.Collections.emptyList();
      } else {
        function_ = null;
        functionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (gradientBuilder_ == null) {
        gradient_ = java.util.Collections.emptyList();
      } else {
        gradient_ = null;
        gradientBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (registeredGradientsBuilder_ == null) {
        registeredGradients_ = java.util.Collections.emptyList();
      } else {
        registeredGradients_ = null;
        registeredGradientsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return graphdef.FunctionProtos.internal_static_uni_model_proto_FunctionDefLibrary_descriptor;
    }

    @java.lang.Override
    public graphdef.FunctionDefLibrary getDefaultInstanceForType() {
      return graphdef.FunctionDefLibrary.getDefaultInstance();
    }

    @java.lang.Override
    public graphdef.FunctionDefLibrary build() {
      graphdef.FunctionDefLibrary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public graphdef.FunctionDefLibrary buildPartial() {
      graphdef.FunctionDefLibrary result = new graphdef.FunctionDefLibrary(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(graphdef.FunctionDefLibrary result) {
      if (functionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          function_ = java.util.Collections.unmodifiableList(function_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.function_ = function_;
      } else {
        result.function_ = functionBuilder_.build();
      }
      if (gradientBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          gradient_ = java.util.Collections.unmodifiableList(gradient_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.gradient_ = gradient_;
      } else {
        result.gradient_ = gradientBuilder_.build();
      }
      if (registeredGradientsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          registeredGradients_ = java.util.Collections.unmodifiableList(registeredGradients_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.registeredGradients_ = registeredGradients_;
      } else {
        result.registeredGradients_ = registeredGradientsBuilder_.build();
      }
    }

    private void buildPartial0(graphdef.FunctionDefLibrary result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof graphdef.FunctionDefLibrary) {
        return mergeFrom((graphdef.FunctionDefLibrary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(graphdef.FunctionDefLibrary other) {
      if (other == graphdef.FunctionDefLibrary.getDefaultInstance()) return this;
      if (functionBuilder_ == null) {
        if (!other.function_.isEmpty()) {
          if (function_.isEmpty()) {
            function_ = other.function_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFunctionIsMutable();
            function_.addAll(other.function_);
          }
          onChanged();
        }
      } else {
        if (!other.function_.isEmpty()) {
          if (functionBuilder_.isEmpty()) {
            functionBuilder_.dispose();
            functionBuilder_ = null;
            function_ = other.function_;
            bitField0_ = (bitField0_ & ~0x00000001);
            functionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFunctionFieldBuilder() : null;
          } else {
            functionBuilder_.addAllMessages(other.function_);
          }
        }
      }
      if (gradientBuilder_ == null) {
        if (!other.gradient_.isEmpty()) {
          if (gradient_.isEmpty()) {
            gradient_ = other.gradient_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureGradientIsMutable();
            gradient_.addAll(other.gradient_);
          }
          onChanged();
        }
      } else {
        if (!other.gradient_.isEmpty()) {
          if (gradientBuilder_.isEmpty()) {
            gradientBuilder_.dispose();
            gradientBuilder_ = null;
            gradient_ = other.gradient_;
            bitField0_ = (bitField0_ & ~0x00000002);
            gradientBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGradientFieldBuilder() : null;
          } else {
            gradientBuilder_.addAllMessages(other.gradient_);
          }
        }
      }
      if (registeredGradientsBuilder_ == null) {
        if (!other.registeredGradients_.isEmpty()) {
          if (registeredGradients_.isEmpty()) {
            registeredGradients_ = other.registeredGradients_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRegisteredGradientsIsMutable();
            registeredGradients_.addAll(other.registeredGradients_);
          }
          onChanged();
        }
      } else {
        if (!other.registeredGradients_.isEmpty()) {
          if (registeredGradientsBuilder_.isEmpty()) {
            registeredGradientsBuilder_.dispose();
            registeredGradientsBuilder_ = null;
            registeredGradients_ = other.registeredGradients_;
            bitField0_ = (bitField0_ & ~0x00000004);
            registeredGradientsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRegisteredGradientsFieldBuilder() : null;
          } else {
            registeredGradientsBuilder_.addAllMessages(other.registeredGradients_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              graphdef.FunctionDef m =
                  input.readMessage(
                      graphdef.FunctionDef.parser(),
                      extensionRegistry);
              if (functionBuilder_ == null) {
                ensureFunctionIsMutable();
                function_.add(m);
              } else {
                functionBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              graphdef.GradientDef m =
                  input.readMessage(
                      graphdef.GradientDef.parser(),
                      extensionRegistry);
              if (gradientBuilder_ == null) {
                ensureGradientIsMutable();
                gradient_.add(m);
              } else {
                gradientBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              graphdef.RegisteredGradient m =
                  input.readMessage(
                      graphdef.RegisteredGradient.parser(),
                      extensionRegistry);
              if (registeredGradientsBuilder_ == null) {
                ensureRegisteredGradientsIsMutable();
                registeredGradients_.add(m);
              } else {
                registeredGradientsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<graphdef.FunctionDef> function_ =
      java.util.Collections.emptyList();
    private void ensureFunctionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        function_ = new java.util.ArrayList<graphdef.FunctionDef>(function_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.FunctionDef, graphdef.FunctionDef.Builder, graphdef.FunctionDefOrBuilder> functionBuilder_;

    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public java.util.List<graphdef.FunctionDef> getFunctionList() {
      if (functionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(function_);
      } else {
        return functionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public int getFunctionCount() {
      if (functionBuilder_ == null) {
        return function_.size();
      } else {
        return functionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public graphdef.FunctionDef getFunction(int index) {
      if (functionBuilder_ == null) {
        return function_.get(index);
      } else {
        return functionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder setFunction(
        int index, graphdef.FunctionDef value) {
      if (functionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionIsMutable();
        function_.set(index, value);
        onChanged();
      } else {
        functionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder setFunction(
        int index, graphdef.FunctionDef.Builder builderForValue) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        function_.set(index, builderForValue.build());
        onChanged();
      } else {
        functionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder addFunction(graphdef.FunctionDef value) {
      if (functionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionIsMutable();
        function_.add(value);
        onChanged();
      } else {
        functionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder addFunction(
        int index, graphdef.FunctionDef value) {
      if (functionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFunctionIsMutable();
        function_.add(index, value);
        onChanged();
      } else {
        functionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder addFunction(
        graphdef.FunctionDef.Builder builderForValue) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        function_.add(builderForValue.build());
        onChanged();
      } else {
        functionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder addFunction(
        int index, graphdef.FunctionDef.Builder builderForValue) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        function_.add(index, builderForValue.build());
        onChanged();
      } else {
        functionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder addAllFunction(
        java.lang.Iterable<? extends graphdef.FunctionDef> values) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, function_);
        onChanged();
      } else {
        functionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder clearFunction() {
      if (functionBuilder_ == null) {
        function_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        functionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public Builder removeFunction(int index) {
      if (functionBuilder_ == null) {
        ensureFunctionIsMutable();
        function_.remove(index);
        onChanged();
      } else {
        functionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public graphdef.FunctionDef.Builder getFunctionBuilder(
        int index) {
      return getFunctionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public graphdef.FunctionDefOrBuilder getFunctionOrBuilder(
        int index) {
      if (functionBuilder_ == null) {
        return function_.get(index);  } else {
        return functionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public java.util.List<? extends graphdef.FunctionDefOrBuilder> 
         getFunctionOrBuilderList() {
      if (functionBuilder_ != null) {
        return functionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(function_);
      }
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public graphdef.FunctionDef.Builder addFunctionBuilder() {
      return getFunctionFieldBuilder().addBuilder(
          graphdef.FunctionDef.getDefaultInstance());
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public graphdef.FunctionDef.Builder addFunctionBuilder(
        int index) {
      return getFunctionFieldBuilder().addBuilder(
          index, graphdef.FunctionDef.getDefaultInstance());
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    public java.util.List<graphdef.FunctionDef.Builder> 
         getFunctionBuilderList() {
      return getFunctionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.FunctionDef, graphdef.FunctionDef.Builder, graphdef.FunctionDefOrBuilder> 
        getFunctionFieldBuilder() {
      if (functionBuilder_ == null) {
        functionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            graphdef.FunctionDef, graphdef.FunctionDef.Builder, graphdef.FunctionDefOrBuilder>(
                function_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        function_ = null;
      }
      return functionBuilder_;
    }

    private java.util.List<graphdef.GradientDef> gradient_ =
      java.util.Collections.emptyList();
    private void ensureGradientIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        gradient_ = new java.util.ArrayList<graphdef.GradientDef>(gradient_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.GradientDef, graphdef.GradientDef.Builder, graphdef.GradientDefOrBuilder> gradientBuilder_;

    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public java.util.List<graphdef.GradientDef> getGradientList() {
      if (gradientBuilder_ == null) {
        return java.util.Collections.unmodifiableList(gradient_);
      } else {
        return gradientBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public int getGradientCount() {
      if (gradientBuilder_ == null) {
        return gradient_.size();
      } else {
        return gradientBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public graphdef.GradientDef getGradient(int index) {
      if (gradientBuilder_ == null) {
        return gradient_.get(index);
      } else {
        return gradientBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder setGradient(
        int index, graphdef.GradientDef value) {
      if (gradientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGradientIsMutable();
        gradient_.set(index, value);
        onChanged();
      } else {
        gradientBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder setGradient(
        int index, graphdef.GradientDef.Builder builderForValue) {
      if (gradientBuilder_ == null) {
        ensureGradientIsMutable();
        gradient_.set(index, builderForValue.build());
        onChanged();
      } else {
        gradientBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder addGradient(graphdef.GradientDef value) {
      if (gradientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGradientIsMutable();
        gradient_.add(value);
        onChanged();
      } else {
        gradientBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder addGradient(
        int index, graphdef.GradientDef value) {
      if (gradientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGradientIsMutable();
        gradient_.add(index, value);
        onChanged();
      } else {
        gradientBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder addGradient(
        graphdef.GradientDef.Builder builderForValue) {
      if (gradientBuilder_ == null) {
        ensureGradientIsMutable();
        gradient_.add(builderForValue.build());
        onChanged();
      } else {
        gradientBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder addGradient(
        int index, graphdef.GradientDef.Builder builderForValue) {
      if (gradientBuilder_ == null) {
        ensureGradientIsMutable();
        gradient_.add(index, builderForValue.build());
        onChanged();
      } else {
        gradientBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder addAllGradient(
        java.lang.Iterable<? extends graphdef.GradientDef> values) {
      if (gradientBuilder_ == null) {
        ensureGradientIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, gradient_);
        onChanged();
      } else {
        gradientBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder clearGradient() {
      if (gradientBuilder_ == null) {
        gradient_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        gradientBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public Builder removeGradient(int index) {
      if (gradientBuilder_ == null) {
        ensureGradientIsMutable();
        gradient_.remove(index);
        onChanged();
      } else {
        gradientBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public graphdef.GradientDef.Builder getGradientBuilder(
        int index) {
      return getGradientFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public graphdef.GradientDefOrBuilder getGradientOrBuilder(
        int index) {
      if (gradientBuilder_ == null) {
        return gradient_.get(index);  } else {
        return gradientBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public java.util.List<? extends graphdef.GradientDefOrBuilder> 
         getGradientOrBuilderList() {
      if (gradientBuilder_ != null) {
        return gradientBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(gradient_);
      }
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public graphdef.GradientDef.Builder addGradientBuilder() {
      return getGradientFieldBuilder().addBuilder(
          graphdef.GradientDef.getDefaultInstance());
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public graphdef.GradientDef.Builder addGradientBuilder(
        int index) {
      return getGradientFieldBuilder().addBuilder(
          index, graphdef.GradientDef.getDefaultInstance());
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    public java.util.List<graphdef.GradientDef.Builder> 
         getGradientBuilderList() {
      return getGradientFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.GradientDef, graphdef.GradientDef.Builder, graphdef.GradientDefOrBuilder> 
        getGradientFieldBuilder() {
      if (gradientBuilder_ == null) {
        gradientBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            graphdef.GradientDef, graphdef.GradientDef.Builder, graphdef.GradientDefOrBuilder>(
                gradient_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        gradient_ = null;
      }
      return gradientBuilder_;
    }

    private java.util.List<graphdef.RegisteredGradient> registeredGradients_ =
      java.util.Collections.emptyList();
    private void ensureRegisteredGradientsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        registeredGradients_ = new java.util.ArrayList<graphdef.RegisteredGradient>(registeredGradients_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.RegisteredGradient, graphdef.RegisteredGradient.Builder, graphdef.RegisteredGradientOrBuilder> registeredGradientsBuilder_;

    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public java.util.List<graphdef.RegisteredGradient> getRegisteredGradientsList() {
      if (registeredGradientsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(registeredGradients_);
      } else {
        return registeredGradientsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public int getRegisteredGradientsCount() {
      if (registeredGradientsBuilder_ == null) {
        return registeredGradients_.size();
      } else {
        return registeredGradientsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public graphdef.RegisteredGradient getRegisteredGradients(int index) {
      if (registeredGradientsBuilder_ == null) {
        return registeredGradients_.get(index);
      } else {
        return registeredGradientsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder setRegisteredGradients(
        int index, graphdef.RegisteredGradient value) {
      if (registeredGradientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegisteredGradientsIsMutable();
        registeredGradients_.set(index, value);
        onChanged();
      } else {
        registeredGradientsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder setRegisteredGradients(
        int index, graphdef.RegisteredGradient.Builder builderForValue) {
      if (registeredGradientsBuilder_ == null) {
        ensureRegisteredGradientsIsMutable();
        registeredGradients_.set(index, builderForValue.build());
        onChanged();
      } else {
        registeredGradientsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder addRegisteredGradients(graphdef.RegisteredGradient value) {
      if (registeredGradientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegisteredGradientsIsMutable();
        registeredGradients_.add(value);
        onChanged();
      } else {
        registeredGradientsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder addRegisteredGradients(
        int index, graphdef.RegisteredGradient value) {
      if (registeredGradientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegisteredGradientsIsMutable();
        registeredGradients_.add(index, value);
        onChanged();
      } else {
        registeredGradientsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder addRegisteredGradients(
        graphdef.RegisteredGradient.Builder builderForValue) {
      if (registeredGradientsBuilder_ == null) {
        ensureRegisteredGradientsIsMutable();
        registeredGradients_.add(builderForValue.build());
        onChanged();
      } else {
        registeredGradientsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder addRegisteredGradients(
        int index, graphdef.RegisteredGradient.Builder builderForValue) {
      if (registeredGradientsBuilder_ == null) {
        ensureRegisteredGradientsIsMutable();
        registeredGradients_.add(index, builderForValue.build());
        onChanged();
      } else {
        registeredGradientsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder addAllRegisteredGradients(
        java.lang.Iterable<? extends graphdef.RegisteredGradient> values) {
      if (registeredGradientsBuilder_ == null) {
        ensureRegisteredGradientsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, registeredGradients_);
        onChanged();
      } else {
        registeredGradientsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder clearRegisteredGradients() {
      if (registeredGradientsBuilder_ == null) {
        registeredGradients_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        registeredGradientsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public Builder removeRegisteredGradients(int index) {
      if (registeredGradientsBuilder_ == null) {
        ensureRegisteredGradientsIsMutable();
        registeredGradients_.remove(index);
        onChanged();
      } else {
        registeredGradientsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public graphdef.RegisteredGradient.Builder getRegisteredGradientsBuilder(
        int index) {
      return getRegisteredGradientsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public graphdef.RegisteredGradientOrBuilder getRegisteredGradientsOrBuilder(
        int index) {
      if (registeredGradientsBuilder_ == null) {
        return registeredGradients_.get(index);  } else {
        return registeredGradientsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public java.util.List<? extends graphdef.RegisteredGradientOrBuilder> 
         getRegisteredGradientsOrBuilderList() {
      if (registeredGradientsBuilder_ != null) {
        return registeredGradientsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(registeredGradients_);
      }
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public graphdef.RegisteredGradient.Builder addRegisteredGradientsBuilder() {
      return getRegisteredGradientsFieldBuilder().addBuilder(
          graphdef.RegisteredGradient.getDefaultInstance());
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public graphdef.RegisteredGradient.Builder addRegisteredGradientsBuilder(
        int index) {
      return getRegisteredGradientsFieldBuilder().addBuilder(
          index, graphdef.RegisteredGradient.getDefaultInstance());
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    public java.util.List<graphdef.RegisteredGradient.Builder> 
         getRegisteredGradientsBuilderList() {
      return getRegisteredGradientsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.RegisteredGradient, graphdef.RegisteredGradient.Builder, graphdef.RegisteredGradientOrBuilder> 
        getRegisteredGradientsFieldBuilder() {
      if (registeredGradientsBuilder_ == null) {
        registeredGradientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            graphdef.RegisteredGradient, graphdef.RegisteredGradient.Builder, graphdef.RegisteredGradientOrBuilder>(
                registeredGradients_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        registeredGradients_ = null;
      }
      return registeredGradientsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:uni_model_proto.FunctionDefLibrary)
  }

  // @@protoc_insertion_point(class_scope:uni_model_proto.FunctionDefLibrary)
  private static final graphdef.FunctionDefLibrary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new graphdef.FunctionDefLibrary();
  }

  public static graphdef.FunctionDefLibrary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FunctionDefLibrary>
      PARSER = new com.google.protobuf.AbstractParser<FunctionDefLibrary>() {
    @java.lang.Override
    public FunctionDefLibrary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FunctionDefLibrary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FunctionDefLibrary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public graphdef.FunctionDefLibrary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

