// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/attr_value.proto

package graphdef;

public interface NameAttrListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uni_model_proto.NameAttrList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
   */
  int getAttrCount();
  /**
   * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
   */
  boolean containsAttr(
      java.lang.String key);
  /**
   * Use {@link #getAttrMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, graphdef.AttrValue>
  getAttr();
  /**
   * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
   */
  java.util.Map<java.lang.String, graphdef.AttrValue>
  getAttrMap();
  /**
   * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
   */
  /* nullable */
graphdef.AttrValue getAttrOrDefault(
      java.lang.String key,
      /* nullable */
graphdef.AttrValue defaultValue);
  /**
   * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
   */
  graphdef.AttrValue getAttrOrThrow(
      java.lang.String key);
}
