// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/node_def.proto

package graphdef;

public final class NodeProto {
  private NodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_NodeDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_NodeDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_NodeDef_AttrEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_NodeDef_AttrEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_NodeDef_ExperimentalDebugInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_NodeDef_ExperimentalDebugInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027graphdef/node_def.proto\022\017uni_model_pro" +
      "to\032\031graphdef/attr_value.proto\"\341\002\n\007NodeDe" +
      "f\022\014\n\004name\030\001 \001(\t\022\n\n\002op\030\002 \001(\t\022\r\n\005input\030\003 \003" +
      "(\t\022\016\n\006device\030\004 \001(\t\0220\n\004attr\030\005 \003(\0132\".uni_m" +
      "odel_proto.NodeDef.AttrEntry\022O\n\027experime" +
      "ntal_debug_info\030\006 \001(\0132..uni_model_proto." +
      "NodeDef.ExperimentalDebugInfo\032G\n\tAttrEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.uni_mod" +
      "el_proto.AttrValue:\0028\001\032Q\n\025ExperimentalDe" +
      "bugInfo\022\033\n\023original_node_names\030\001 \003(\t\022\033\n\023" +
      "original_func_names\030\002 \003(\tBk\n\010graphdefB\tN" +
      "odeProtoP\001ZOgithub.com/tensorflow/tensor" +
      "flow/tensorflow/go/core/framework/node_d" +
      "ef_go_proto\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          graphdef.AttrValueProtos.getDescriptor(),
        });
    internal_static_uni_model_proto_NodeDef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uni_model_proto_NodeDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_NodeDef_descriptor,
        new java.lang.String[] { "Name", "Op", "Input", "Device", "Attr", "ExperimentalDebugInfo", });
    internal_static_uni_model_proto_NodeDef_AttrEntry_descriptor =
      internal_static_uni_model_proto_NodeDef_descriptor.getNestedTypes().get(0);
    internal_static_uni_model_proto_NodeDef_AttrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_NodeDef_AttrEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_uni_model_proto_NodeDef_ExperimentalDebugInfo_descriptor =
      internal_static_uni_model_proto_NodeDef_descriptor.getNestedTypes().get(1);
    internal_static_uni_model_proto_NodeDef_ExperimentalDebugInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_NodeDef_ExperimentalDebugInfo_descriptor,
        new java.lang.String[] { "OriginalNodeNames", "OriginalFuncNames", });
    graphdef.AttrValueProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
