// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/resource_handle.proto

// Protobuf Java Version: 3.25.3
package graphdef;

public final class ResourceHandle {
  private ResourceHandle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_ResourceHandleProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_ResourceHandleProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_ResourceHandleProto_DtypeAndShape_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_ResourceHandleProto_DtypeAndShape_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036graphdef/resource_handle.proto\022\017uni_mo" +
      "del_proto\032\033graphdef/tensor_shape.proto\032\024" +
      "graphdef/types.proto\"\264\002\n\023ResourceHandleP" +
      "roto\022\016\n\006device\030\001 \001(\t\022\021\n\tcontainer\030\002 \001(\t\022" +
      "\014\n\004name\030\003 \001(\t\022\021\n\thash_code\030\004 \001(\004\022\027\n\017mayb" +
      "e_type_name\030\005 \001(\t\022M\n\021dtypes_and_shapes\030\006" +
      " \003(\01322.uni_model_proto.ResourceHandlePro" +
      "to.DtypeAndShape\032k\n\rDtypeAndShape\022(\n\005dty" +
      "pe\030\001 \001(\0162\031.uni_model_proto.DataType\0220\n\005s" +
      "hape\030\002 \001(\0132!.uni_model_proto.TensorShape" +
      "ProtoJ\004\010\007\020\010Bw\n\010graphdefB\016ResourceHandleP" +
      "\001ZVgithub.com/tensorflow/tensorflow/tens" +
      "orflow/go/core/framework/resource_handle" +
      "_go_proto\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          graphdef.TensorShapeProtos.getDescriptor(),
          graphdef.TypesProtos.getDescriptor(),
        });
    internal_static_uni_model_proto_ResourceHandleProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uni_model_proto_ResourceHandleProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_ResourceHandleProto_descriptor,
        new java.lang.String[] { "Device", "Container", "Name", "HashCode", "MaybeTypeName", "DtypesAndShapes", });
    internal_static_uni_model_proto_ResourceHandleProto_DtypeAndShape_descriptor =
      internal_static_uni_model_proto_ResourceHandleProto_descriptor.getNestedTypes().get(0);
    internal_static_uni_model_proto_ResourceHandleProto_DtypeAndShape_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_ResourceHandleProto_DtypeAndShape_descriptor,
        new java.lang.String[] { "Dtype", "Shape", });
    graphdef.TensorShapeProtos.getDescriptor();
    graphdef.TypesProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
