// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/tensor.proto

// Protobuf Java Version: 3.25.3
package graphdef;

public final class TensorProtos {
  private TensorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_TensorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_TensorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uni_model_proto_VariantTensorDataProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uni_model_proto_VariantTensorDataProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025graphdef/tensor.proto\022\017uni_model_proto" +
      "\032\036graphdef/resource_handle.proto\032\033graphd" +
      "ef/tensor_shape.proto\032\024graphdef/types.pr" +
      "oto\"\240\004\n\013TensorProto\022(\n\005dtype\030\001 \001(\0162\031.uni" +
      "_model_proto.DataType\0227\n\014tensor_shape\030\002 " +
      "\001(\0132!.uni_model_proto.TensorShapeProto\022\026" +
      "\n\016version_number\030\003 \001(\005\022\026\n\016tensor_content" +
      "\030\004 \001(\014\022\024\n\010half_val\030\r \003(\005B\002\020\001\022\025\n\tfloat_va" +
      "l\030\005 \003(\002B\002\020\001\022\026\n\ndouble_val\030\006 \003(\001B\002\020\001\022\023\n\007i" +
      "nt_val\030\007 \003(\005B\002\020\001\022\022\n\nstring_val\030\010 \003(\014\022\030\n\014" +
      "scomplex_val\030\t \003(\002B\002\020\001\022\025\n\tint64_val\030\n \003(" +
      "\003B\002\020\001\022\024\n\010bool_val\030\013 \003(\010B\002\020\001\022\030\n\014dcomplex_" +
      "val\030\014 \003(\001B\002\020\001\022A\n\023resource_handle_val\030\016 \003" +
      "(\0132$.uni_model_proto.ResourceHandleProto" +
      "\022<\n\013variant_val\030\017 \003(\0132\'.uni_model_proto." +
      "VariantTensorDataProto\022\026\n\nuint32_val\030\020 \003" +
      "(\rB\002\020\001\022\026\n\nuint64_val\030\021 \003(\004B\002\020\001\"l\n\026Varian" +
      "tTensorDataProto\022\021\n\ttype_name\030\001 \001(\t\022\020\n\010m" +
      "etadata\030\002 \001(\014\022-\n\007tensors\030\003 \003(\0132\034.uni_mod" +
      "el_proto.TensorProtoBl\n\010graphdefB\014Tensor" +
      "ProtosP\001ZMgithub.com/tensorflow/tensorfl" +
      "ow/tensorflow/go/core/framework/tensor_g" +
      "o_proto\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          graphdef.ResourceHandle.getDescriptor(),
          graphdef.TensorShapeProtos.getDescriptor(),
          graphdef.TypesProtos.getDescriptor(),
        });
    internal_static_uni_model_proto_TensorProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uni_model_proto_TensorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_TensorProto_descriptor,
        new java.lang.String[] { "Dtype", "TensorShape", "VersionNumber", "TensorContent", "HalfVal", "FloatVal", "DoubleVal", "IntVal", "StringVal", "ScomplexVal", "Int64Val", "BoolVal", "DcomplexVal", "ResourceHandleVal", "VariantVal", "Uint32Val", "Uint64Val", });
    internal_static_uni_model_proto_VariantTensorDataProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_uni_model_proto_VariantTensorDataProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uni_model_proto_VariantTensorDataProto_descriptor,
        new java.lang.String[] { "TypeName", "Metadata", "Tensors", });
    graphdef.ResourceHandle.getDescriptor();
    graphdef.TensorShapeProtos.getDescriptor();
    graphdef.TypesProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
