// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/tensor_shape.proto

// Protobuf Java Version: 3.25.3
package graphdef;

/**
 * <pre>
 * Dimensions of a tensor.
 * </pre>
 *
 * Protobuf type {@code uni_model_proto.TensorShapeProto}
 */
public final class TensorShapeProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:uni_model_proto.TensorShapeProto)
    TensorShapeProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TensorShapeProto.newBuilder() to construct.
  private TensorShapeProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TensorShapeProto() {
    dim_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TensorShapeProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            graphdef.TensorShapeProto.class, graphdef.TensorShapeProto.Builder.class);
  }

  public interface DimOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uni_model_proto.TensorShapeProto.Dim)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Size of the tensor in that dimension.
     * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
     * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
     * that work with TensorShapeProto may fail at runtime when deserializing
     * a TensorShapeProto containing a dim value of -1.
     * </pre>
     *
     * <code>int64 size = 1;</code>
     * @return The size.
     */
    long getSize();

    /**
     * <pre>
     * Optional name of the tensor dimension.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Optional name of the tensor dimension.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   * One dimension of the tensor.
   * </pre>
   *
   * Protobuf type {@code uni_model_proto.TensorShapeProto.Dim}
   */
  public static final class Dim extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:uni_model_proto.TensorShapeProto.Dim)
      DimOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dim.newBuilder() to construct.
    private Dim(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dim() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dim();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_Dim_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_Dim_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              graphdef.TensorShapeProto.Dim.class, graphdef.TensorShapeProto.Dim.Builder.class);
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private long size_ = 0L;
    /**
     * <pre>
     * Size of the tensor in that dimension.
     * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
     * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
     * that work with TensorShapeProto may fail at runtime when deserializing
     * a TensorShapeProto containing a dim value of -1.
     * </pre>
     *
     * <code>int64 size = 1;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * Optional name of the tensor dimension.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional name of the tensor dimension.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (size_ != 0L) {
        output.writeInt64(1, size_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, size_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof graphdef.TensorShapeProto.Dim)) {
        return super.equals(obj);
      }
      graphdef.TensorShapeProto.Dim other = (graphdef.TensorShapeProto.Dim) obj;

      if (getSize()
          != other.getSize()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static graphdef.TensorShapeProto.Dim parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static graphdef.TensorShapeProto.Dim parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static graphdef.TensorShapeProto.Dim parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static graphdef.TensorShapeProto.Dim parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(graphdef.TensorShapeProto.Dim prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * One dimension of the tensor.
     * </pre>
     *
     * Protobuf type {@code uni_model_proto.TensorShapeProto.Dim}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uni_model_proto.TensorShapeProto.Dim)
        graphdef.TensorShapeProto.DimOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_Dim_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_Dim_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                graphdef.TensorShapeProto.Dim.class, graphdef.TensorShapeProto.Dim.Builder.class);
      }

      // Construct using graphdef.TensorShapeProto.Dim.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        size_ = 0L;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_Dim_descriptor;
      }

      @java.lang.Override
      public graphdef.TensorShapeProto.Dim getDefaultInstanceForType() {
        return graphdef.TensorShapeProto.Dim.getDefaultInstance();
      }

      @java.lang.Override
      public graphdef.TensorShapeProto.Dim build() {
        graphdef.TensorShapeProto.Dim result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public graphdef.TensorShapeProto.Dim buildPartial() {
        graphdef.TensorShapeProto.Dim result = new graphdef.TensorShapeProto.Dim(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(graphdef.TensorShapeProto.Dim result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.size_ = size_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof graphdef.TensorShapeProto.Dim) {
          return mergeFrom((graphdef.TensorShapeProto.Dim)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(graphdef.TensorShapeProto.Dim other) {
        if (other == graphdef.TensorShapeProto.Dim.getDefaultInstance()) return this;
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                size_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long size_ ;
      /**
       * <pre>
       * Size of the tensor in that dimension.
       * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * </pre>
       *
       * <code>int64 size = 1;</code>
       * @return The size.
       */
      @java.lang.Override
      public long getSize() {
        return size_;
      }
      /**
       * <pre>
       * Size of the tensor in that dimension.
       * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * </pre>
       *
       * <code>int64 size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(long value) {

        size_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Size of the tensor in that dimension.
       * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * </pre>
       *
       * <code>int64 size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:uni_model_proto.TensorShapeProto.Dim)
    }

    // @@protoc_insertion_point(class_scope:uni_model_proto.TensorShapeProto.Dim)
    private static final graphdef.TensorShapeProto.Dim DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new graphdef.TensorShapeProto.Dim();
    }

    public static graphdef.TensorShapeProto.Dim getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dim>
        PARSER = new com.google.protobuf.AbstractParser<Dim>() {
      @java.lang.Override
      public Dim parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Dim> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dim> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public graphdef.TensorShapeProto.Dim getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int DIM_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<graphdef.TensorShapeProto.Dim> dim_;
  /**
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   *
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   *
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   *
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   *
   * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
   */
  @java.lang.Override
  public java.util.List<graphdef.TensorShapeProto.Dim> getDimList() {
    return dim_;
  }
  /**
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   *
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   *
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   *
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   *
   * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends graphdef.TensorShapeProto.DimOrBuilder> 
      getDimOrBuilderList() {
    return dim_;
  }
  /**
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   *
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   *
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   *
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   *
   * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
   */
  @java.lang.Override
  public int getDimCount() {
    return dim_.size();
  }
  /**
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   *
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   *
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   *
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   *
   * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
   */
  @java.lang.Override
  public graphdef.TensorShapeProto.Dim getDim(int index) {
    return dim_.get(index);
  }
  /**
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   *
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   *
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   *
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   *
   * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
   */
  @java.lang.Override
  public graphdef.TensorShapeProto.DimOrBuilder getDimOrBuilder(
      int index) {
    return dim_.get(index);
  }

  public static final int UNKNOWN_RANK_FIELD_NUMBER = 3;
  private boolean unknownRank_ = false;
  /**
   * <pre>
   * If true, the number of dimensions in the shape is unknown.
   *
   * If true, "dim.size()" must be 0.
   * </pre>
   *
   * <code>bool unknown_rank = 3;</code>
   * @return The unknownRank.
   */
  @java.lang.Override
  public boolean getUnknownRank() {
    return unknownRank_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dim_.size(); i++) {
      output.writeMessage(2, dim_.get(i));
    }
    if (unknownRank_ != false) {
      output.writeBool(3, unknownRank_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dim_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, dim_.get(i));
    }
    if (unknownRank_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, unknownRank_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof graphdef.TensorShapeProto)) {
      return super.equals(obj);
    }
    graphdef.TensorShapeProto other = (graphdef.TensorShapeProto) obj;

    if (!getDimList()
        .equals(other.getDimList())) return false;
    if (getUnknownRank()
        != other.getUnknownRank()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDimCount() > 0) {
      hash = (37 * hash) + DIM_FIELD_NUMBER;
      hash = (53 * hash) + getDimList().hashCode();
    }
    hash = (37 * hash) + UNKNOWN_RANK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUnknownRank());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static graphdef.TensorShapeProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.TensorShapeProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.TensorShapeProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.TensorShapeProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.TensorShapeProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static graphdef.TensorShapeProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static graphdef.TensorShapeProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static graphdef.TensorShapeProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static graphdef.TensorShapeProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static graphdef.TensorShapeProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static graphdef.TensorShapeProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static graphdef.TensorShapeProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(graphdef.TensorShapeProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Dimensions of a tensor.
   * </pre>
   *
   * Protobuf type {@code uni_model_proto.TensorShapeProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:uni_model_proto.TensorShapeProto)
      graphdef.TensorShapeProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              graphdef.TensorShapeProto.class, graphdef.TensorShapeProto.Builder.class);
    }

    // Construct using graphdef.TensorShapeProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (dimBuilder_ == null) {
        dim_ = java.util.Collections.emptyList();
      } else {
        dim_ = null;
        dimBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      unknownRank_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return graphdef.TensorShapeProtos.internal_static_uni_model_proto_TensorShapeProto_descriptor;
    }

    @java.lang.Override
    public graphdef.TensorShapeProto getDefaultInstanceForType() {
      return graphdef.TensorShapeProto.getDefaultInstance();
    }

    @java.lang.Override
    public graphdef.TensorShapeProto build() {
      graphdef.TensorShapeProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public graphdef.TensorShapeProto buildPartial() {
      graphdef.TensorShapeProto result = new graphdef.TensorShapeProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(graphdef.TensorShapeProto result) {
      if (dimBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          dim_ = java.util.Collections.unmodifiableList(dim_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dim_ = dim_;
      } else {
        result.dim_ = dimBuilder_.build();
      }
    }

    private void buildPartial0(graphdef.TensorShapeProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.unknownRank_ = unknownRank_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof graphdef.TensorShapeProto) {
        return mergeFrom((graphdef.TensorShapeProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(graphdef.TensorShapeProto other) {
      if (other == graphdef.TensorShapeProto.getDefaultInstance()) return this;
      if (dimBuilder_ == null) {
        if (!other.dim_.isEmpty()) {
          if (dim_.isEmpty()) {
            dim_ = other.dim_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDimIsMutable();
            dim_.addAll(other.dim_);
          }
          onChanged();
        }
      } else {
        if (!other.dim_.isEmpty()) {
          if (dimBuilder_.isEmpty()) {
            dimBuilder_.dispose();
            dimBuilder_ = null;
            dim_ = other.dim_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dimBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDimFieldBuilder() : null;
          } else {
            dimBuilder_.addAllMessages(other.dim_);
          }
        }
      }
      if (other.getUnknownRank() != false) {
        setUnknownRank(other.getUnknownRank());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              graphdef.TensorShapeProto.Dim m =
                  input.readMessage(
                      graphdef.TensorShapeProto.Dim.parser(),
                      extensionRegistry);
              if (dimBuilder_ == null) {
                ensureDimIsMutable();
                dim_.add(m);
              } else {
                dimBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              unknownRank_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<graphdef.TensorShapeProto.Dim> dim_ =
      java.util.Collections.emptyList();
    private void ensureDimIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        dim_ = new java.util.ArrayList<graphdef.TensorShapeProto.Dim>(dim_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.TensorShapeProto.Dim, graphdef.TensorShapeProto.Dim.Builder, graphdef.TensorShapeProto.DimOrBuilder> dimBuilder_;

    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public java.util.List<graphdef.TensorShapeProto.Dim> getDimList() {
      if (dimBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dim_);
      } else {
        return dimBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public int getDimCount() {
      if (dimBuilder_ == null) {
        return dim_.size();
      } else {
        return dimBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public graphdef.TensorShapeProto.Dim getDim(int index) {
      if (dimBuilder_ == null) {
        return dim_.get(index);
      } else {
        return dimBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder setDim(
        int index, graphdef.TensorShapeProto.Dim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.set(index, value);
        onChanged();
      } else {
        dimBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder setDim(
        int index, graphdef.TensorShapeProto.Dim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.set(index, builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder addDim(graphdef.TensorShapeProto.Dim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.add(value);
        onChanged();
      } else {
        dimBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder addDim(
        int index, graphdef.TensorShapeProto.Dim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.add(index, value);
        onChanged();
      } else {
        dimBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder addDim(
        graphdef.TensorShapeProto.Dim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.add(builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder addDim(
        int index, graphdef.TensorShapeProto.Dim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.add(index, builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder addAllDim(
        java.lang.Iterable<? extends graphdef.TensorShapeProto.Dim> values) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dim_);
        onChanged();
      } else {
        dimBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder clearDim() {
      if (dimBuilder_ == null) {
        dim_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dimBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public Builder removeDim(int index) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.remove(index);
        onChanged();
      } else {
        dimBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public graphdef.TensorShapeProto.Dim.Builder getDimBuilder(
        int index) {
      return getDimFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public graphdef.TensorShapeProto.DimOrBuilder getDimOrBuilder(
        int index) {
      if (dimBuilder_ == null) {
        return dim_.get(index);  } else {
        return dimBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public java.util.List<? extends graphdef.TensorShapeProto.DimOrBuilder> 
         getDimOrBuilderList() {
      if (dimBuilder_ != null) {
        return dimBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dim_);
      }
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public graphdef.TensorShapeProto.Dim.Builder addDimBuilder() {
      return getDimFieldBuilder().addBuilder(
          graphdef.TensorShapeProto.Dim.getDefaultInstance());
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public graphdef.TensorShapeProto.Dim.Builder addDimBuilder(
        int index) {
      return getDimFieldBuilder().addBuilder(
          index, graphdef.TensorShapeProto.Dim.getDefaultInstance());
    }
    /**
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     *
     * <code>repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;</code>
     */
    public java.util.List<graphdef.TensorShapeProto.Dim.Builder> 
         getDimBuilderList() {
      return getDimFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        graphdef.TensorShapeProto.Dim, graphdef.TensorShapeProto.Dim.Builder, graphdef.TensorShapeProto.DimOrBuilder> 
        getDimFieldBuilder() {
      if (dimBuilder_ == null) {
        dimBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            graphdef.TensorShapeProto.Dim, graphdef.TensorShapeProto.Dim.Builder, graphdef.TensorShapeProto.DimOrBuilder>(
                dim_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        dim_ = null;
      }
      return dimBuilder_;
    }

    private boolean unknownRank_ ;
    /**
     * <pre>
     * If true, the number of dimensions in the shape is unknown.
     *
     * If true, "dim.size()" must be 0.
     * </pre>
     *
     * <code>bool unknown_rank = 3;</code>
     * @return The unknownRank.
     */
    @java.lang.Override
    public boolean getUnknownRank() {
      return unknownRank_;
    }
    /**
     * <pre>
     * If true, the number of dimensions in the shape is unknown.
     *
     * If true, "dim.size()" must be 0.
     * </pre>
     *
     * <code>bool unknown_rank = 3;</code>
     * @param value The unknownRank to set.
     * @return This builder for chaining.
     */
    public Builder setUnknownRank(boolean value) {

      unknownRank_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, the number of dimensions in the shape is unknown.
     *
     * If true, "dim.size()" must be 0.
     * </pre>
     *
     * <code>bool unknown_rank = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnknownRank() {
      bitField0_ = (bitField0_ & ~0x00000002);
      unknownRank_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:uni_model_proto.TensorShapeProto)
  }

  // @@protoc_insertion_point(class_scope:uni_model_proto.TensorShapeProto)
  private static final graphdef.TensorShapeProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new graphdef.TensorShapeProto();
  }

  public static graphdef.TensorShapeProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TensorShapeProto>
      PARSER = new com.google.protobuf.AbstractParser<TensorShapeProto>() {
    @java.lang.Override
    public TensorShapeProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TensorShapeProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TensorShapeProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public graphdef.TensorShapeProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

