// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphdef/types.proto

// Protobuf Java Version: 3.25.3
package graphdef;

public final class TypesProtos {
  private TypesProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024graphdef/types.proto\022\017uni_model_proto*" +
      "\252\006\n\010DataType\022\016\n\nDT_INVALID\020\000\022\014\n\010DT_FLOAT" +
      "\020\001\022\r\n\tDT_DOUBLE\020\002\022\014\n\010DT_INT32\020\003\022\014\n\010DT_UI" +
      "NT8\020\004\022\014\n\010DT_INT16\020\005\022\013\n\007DT_INT8\020\006\022\r\n\tDT_S" +
      "TRING\020\007\022\020\n\014DT_COMPLEX64\020\010\022\014\n\010DT_INT64\020\t\022" +
      "\013\n\007DT_BOOL\020\n\022\014\n\010DT_QINT8\020\013\022\r\n\tDT_QUINT8\020" +
      "\014\022\r\n\tDT_QINT32\020\r\022\017\n\013DT_BFLOAT16\020\016\022\r\n\tDT_" +
      "QINT16\020\017\022\016\n\nDT_QUINT16\020\020\022\r\n\tDT_UINT16\020\021\022" +
      "\021\n\rDT_COMPLEX128\020\022\022\013\n\007DT_HALF\020\023\022\017\n\013DT_RE" +
      "SOURCE\020\024\022\016\n\nDT_VARIANT\020\025\022\r\n\tDT_UINT32\020\026\022" +
      "\r\n\tDT_UINT64\020\027\022\020\n\014DT_FLOAT_REF\020e\022\021\n\rDT_D" +
      "OUBLE_REF\020f\022\020\n\014DT_INT32_REF\020g\022\020\n\014DT_UINT" +
      "8_REF\020h\022\020\n\014DT_INT16_REF\020i\022\017\n\013DT_INT8_REF" +
      "\020j\022\021\n\rDT_STRING_REF\020k\022\024\n\020DT_COMPLEX64_RE" +
      "F\020l\022\020\n\014DT_INT64_REF\020m\022\017\n\013DT_BOOL_REF\020n\022\020" +
      "\n\014DT_QINT8_REF\020o\022\021\n\rDT_QUINT8_REF\020p\022\021\n\rD" +
      "T_QINT32_REF\020q\022\023\n\017DT_BFLOAT16_REF\020r\022\021\n\rD" +
      "T_QINT16_REF\020s\022\022\n\016DT_QUINT16_REF\020t\022\021\n\rDT" +
      "_UINT16_REF\020u\022\025\n\021DT_COMPLEX128_REF\020v\022\017\n\013" +
      "DT_HALF_REF\020w\022\023\n\017DT_RESOURCE_REF\020x\022\022\n\016DT" +
      "_VARIANT_REF\020y\022\021\n\rDT_UINT32_REF\020z\022\021\n\rDT_" +
      "UINT64_REF\020{Bj\n\010graphdefB\013TypesProtosP\001Z" +
      "Lgithub.com/tensorflow/tensorflow/tensor" +
      "flow/go/core/framework/types_go_proto\370\001\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
