// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: graphdef/attr_value.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package graphdef;

