//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: graphdef/function.proto

package graphdef;

@kotlin.jvm.JvmName("-initializefunctionDefLibrary")
public inline fun functionDefLibrary(block: graphdef.FunctionDefLibraryKt.Dsl.() -> kotlin.Unit): graphdef.FunctionDefLibrary =
  graphdef.FunctionDefLibraryKt.Dsl._create(graphdef.FunctionDefLibrary.newBuilder()).apply { block() }._build()
public object FunctionDefLibraryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: graphdef.FunctionDefLibrary.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: graphdef.FunctionDefLibrary.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): graphdef.FunctionDefLibrary = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FunctionProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
     public val function: com.google.protobuf.kotlin.DslList<graphdef.FunctionDef, FunctionProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFunctionList()
      )
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     * @param value The function to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFunction")
    public fun com.google.protobuf.kotlin.DslList<graphdef.FunctionDef, FunctionProxy>.add(value: graphdef.FunctionDef) {
      _builder.addFunction(value)
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     * @param value The function to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFunction")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.FunctionDef, FunctionProxy>.plusAssign(value: graphdef.FunctionDef) {
      add(value)
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     * @param values The function to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFunction")
    public fun com.google.protobuf.kotlin.DslList<graphdef.FunctionDef, FunctionProxy>.addAll(values: kotlin.collections.Iterable<graphdef.FunctionDef>) {
      _builder.addAllFunction(values)
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     * @param values The function to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFunction")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.FunctionDef, FunctionProxy>.plusAssign(values: kotlin.collections.Iterable<graphdef.FunctionDef>) {
      addAll(values)
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     * @param index The index to set the value at.
     * @param value The function to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFunction")
    public operator fun com.google.protobuf.kotlin.DslList<graphdef.FunctionDef, FunctionProxy>.set(index: kotlin.Int, value: graphdef.FunctionDef) {
      _builder.setFunction(index, value)
    }
    /**
     * <code>repeated .uni_model_proto.FunctionDef function = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFunction")
    public fun com.google.protobuf.kotlin.DslList<graphdef.FunctionDef, FunctionProxy>.clear() {
      _builder.clearFunction()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class GradientProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
     public val gradient: com.google.protobuf.kotlin.DslList<graphdef.GradientDef, GradientProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getGradientList()
      )
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     * @param value The gradient to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addGradient")
    public fun com.google.protobuf.kotlin.DslList<graphdef.GradientDef, GradientProxy>.add(value: graphdef.GradientDef) {
      _builder.addGradient(value)
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     * @param value The gradient to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignGradient")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.GradientDef, GradientProxy>.plusAssign(value: graphdef.GradientDef) {
      add(value)
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     * @param values The gradient to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllGradient")
    public fun com.google.protobuf.kotlin.DslList<graphdef.GradientDef, GradientProxy>.addAll(values: kotlin.collections.Iterable<graphdef.GradientDef>) {
      _builder.addAllGradient(values)
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     * @param values The gradient to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllGradient")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.GradientDef, GradientProxy>.plusAssign(values: kotlin.collections.Iterable<graphdef.GradientDef>) {
      addAll(values)
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     * @param index The index to set the value at.
     * @param value The gradient to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setGradient")
    public operator fun com.google.protobuf.kotlin.DslList<graphdef.GradientDef, GradientProxy>.set(index: kotlin.Int, value: graphdef.GradientDef) {
      _builder.setGradient(index, value)
    }
    /**
     * <code>repeated .uni_model_proto.GradientDef gradient = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearGradient")
    public fun com.google.protobuf.kotlin.DslList<graphdef.GradientDef, GradientProxy>.clear() {
      _builder.clearGradient()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RegisteredGradientsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
     public val registeredGradients: com.google.protobuf.kotlin.DslList<graphdef.RegisteredGradient, RegisteredGradientsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRegisteredGradientsList()
      )
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     * @param value The registeredGradients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRegisteredGradients")
    public fun com.google.protobuf.kotlin.DslList<graphdef.RegisteredGradient, RegisteredGradientsProxy>.add(value: graphdef.RegisteredGradient) {
      _builder.addRegisteredGradients(value)
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     * @param value The registeredGradients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRegisteredGradients")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.RegisteredGradient, RegisteredGradientsProxy>.plusAssign(value: graphdef.RegisteredGradient) {
      add(value)
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     * @param values The registeredGradients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRegisteredGradients")
    public fun com.google.protobuf.kotlin.DslList<graphdef.RegisteredGradient, RegisteredGradientsProxy>.addAll(values: kotlin.collections.Iterable<graphdef.RegisteredGradient>) {
      _builder.addAllRegisteredGradients(values)
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     * @param values The registeredGradients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRegisteredGradients")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.RegisteredGradient, RegisteredGradientsProxy>.plusAssign(values: kotlin.collections.Iterable<graphdef.RegisteredGradient>) {
      addAll(values)
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     * @param index The index to set the value at.
     * @param value The registeredGradients to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRegisteredGradients")
    public operator fun com.google.protobuf.kotlin.DslList<graphdef.RegisteredGradient, RegisteredGradientsProxy>.set(index: kotlin.Int, value: graphdef.RegisteredGradient) {
      _builder.setRegisteredGradients(index, value)
    }
    /**
     * <code>repeated .uni_model_proto.RegisteredGradient registered_gradients = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRegisteredGradients")
    public fun com.google.protobuf.kotlin.DslList<graphdef.RegisteredGradient, RegisteredGradientsProxy>.clear() {
      _builder.clearRegisteredGradients()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun graphdef.FunctionDefLibrary.copy(block: graphdef.FunctionDefLibraryKt.Dsl.() -> kotlin.Unit): graphdef.FunctionDefLibrary =
  graphdef.FunctionDefLibraryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

