//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: graphdef/function.proto

package graphdef;

@kotlin.jvm.JvmName("-initializegradientDef")
public inline fun gradientDef(block: graphdef.GradientDefKt.Dsl.() -> kotlin.Unit): graphdef.GradientDef =
  graphdef.GradientDefKt.Dsl._create(graphdef.GradientDef.newBuilder()).apply { block() }._build()
public object GradientDefKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: graphdef.GradientDef.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: graphdef.GradientDef.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): graphdef.GradientDef = _builder.build()

    /**
     * <pre>
     * The function name.
     * </pre>
     *
     * <code>string function_name = 1;</code>
     */
    public var functionName: kotlin.String
      @JvmName("getFunctionName")
      get() = _builder.getFunctionName()
      @JvmName("setFunctionName")
      set(value) {
        _builder.setFunctionName(value)
      }
    /**
     * <pre>
     * The function name.
     * </pre>
     *
     * <code>string function_name = 1;</code>
     */
    public fun clearFunctionName() {
      _builder.clearFunctionName()
    }

    /**
     * <pre>
     * The gradient function's name.
     * </pre>
     *
     * <code>string gradient_func = 2;</code>
     */
    public var gradientFunc: kotlin.String
      @JvmName("getGradientFunc")
      get() = _builder.getGradientFunc()
      @JvmName("setGradientFunc")
      set(value) {
        _builder.setGradientFunc(value)
      }
    /**
     * <pre>
     * The gradient function's name.
     * </pre>
     *
     * <code>string gradient_func = 2;</code>
     */
    public fun clearGradientFunc() {
      _builder.clearGradientFunc()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun graphdef.GradientDef.copy(block: graphdef.GradientDefKt.Dsl.() -> kotlin.Unit): graphdef.GradientDef =
  graphdef.GradientDefKt.Dsl._create(this.toBuilder()).apply { block() }._build()

