//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: graphdef/attr_value.proto

package graphdef;

@kotlin.jvm.JvmName("-initializenameAttrList")
public inline fun nameAttrList(block: graphdef.NameAttrListKt.Dsl.() -> kotlin.Unit): graphdef.NameAttrList =
  graphdef.NameAttrListKt.Dsl._create(graphdef.NameAttrList.newBuilder()).apply { block() }._build()
public object NameAttrListKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: graphdef.NameAttrList.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: graphdef.NameAttrList.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): graphdef.NameAttrList = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AttrProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
     */
     public val attr: com.google.protobuf.kotlin.DslMap<kotlin.String, graphdef.AttrValue, AttrProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getAttrMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getAttrMap()
      )
    /**
     * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
     */
    @JvmName("putAttr")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, graphdef.AttrValue, AttrProxy>
      .put(key: kotlin.String, value: graphdef.AttrValue) {
         _builder.putAttr(key, value)
       }
    /**
     * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setAttr")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, graphdef.AttrValue, AttrProxy>
      .set(key: kotlin.String, value: graphdef.AttrValue) {
         put(key, value)
       }
    /**
     * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeAttr")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, graphdef.AttrValue, AttrProxy>
      .remove(key: kotlin.String) {
         _builder.removeAttr(key)
       }
    /**
     * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllAttr")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, graphdef.AttrValue, AttrProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, graphdef.AttrValue>) {
         _builder.putAllAttr(map)
       }
    /**
     * <code>map&lt;string, .uni_model_proto.AttrValue&gt; attr = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearAttr")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, graphdef.AttrValue, AttrProxy>
      .clear() {
         _builder.clearAttr()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun graphdef.NameAttrList.copy(block: graphdef.NameAttrListKt.Dsl.() -> kotlin.Unit): graphdef.NameAttrList =
  graphdef.NameAttrListKt.Dsl._create(this.toBuilder()).apply { block() }._build()

