//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: graphdef/op_def.proto

package graphdef;

@kotlin.jvm.JvmName("-initializeopList")
public inline fun opList(block: graphdef.OpListKt.Dsl.() -> kotlin.Unit): graphdef.OpList =
  graphdef.OpListKt.Dsl._create(graphdef.OpList.newBuilder()).apply { block() }._build()
public object OpListKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: graphdef.OpList.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: graphdef.OpList.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): graphdef.OpList = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OpProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .uni_model_proto.OpDef op = 1;</code>
     */
     public val op: com.google.protobuf.kotlin.DslList<graphdef.OpDef, OpProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOpList()
      )
    /**
     * <code>repeated .uni_model_proto.OpDef op = 1;</code>
     * @param value The op to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOp")
    public fun com.google.protobuf.kotlin.DslList<graphdef.OpDef, OpProxy>.add(value: graphdef.OpDef) {
      _builder.addOp(value)
    }
    /**
     * <code>repeated .uni_model_proto.OpDef op = 1;</code>
     * @param value The op to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOp")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.OpDef, OpProxy>.plusAssign(value: graphdef.OpDef) {
      add(value)
    }
    /**
     * <code>repeated .uni_model_proto.OpDef op = 1;</code>
     * @param values The op to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOp")
    public fun com.google.protobuf.kotlin.DslList<graphdef.OpDef, OpProxy>.addAll(values: kotlin.collections.Iterable<graphdef.OpDef>) {
      _builder.addAllOp(values)
    }
    /**
     * <code>repeated .uni_model_proto.OpDef op = 1;</code>
     * @param values The op to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOp")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.OpDef, OpProxy>.plusAssign(values: kotlin.collections.Iterable<graphdef.OpDef>) {
      addAll(values)
    }
    /**
     * <code>repeated .uni_model_proto.OpDef op = 1;</code>
     * @param index The index to set the value at.
     * @param value The op to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOp")
    public operator fun com.google.protobuf.kotlin.DslList<graphdef.OpDef, OpProxy>.set(index: kotlin.Int, value: graphdef.OpDef) {
      _builder.setOp(index, value)
    }
    /**
     * <code>repeated .uni_model_proto.OpDef op = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOp")
    public fun com.google.protobuf.kotlin.DslList<graphdef.OpDef, OpProxy>.clear() {
      _builder.clearOp()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun graphdef.OpList.copy(block: graphdef.OpListKt.Dsl.() -> kotlin.Unit): graphdef.OpList =
  graphdef.OpListKt.Dsl._create(this.toBuilder()).apply { block() }._build()

