//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: graphdef/function.proto

package graphdef;

@kotlin.jvm.JvmName("-initializeregisteredGradient")
public inline fun registeredGradient(block: graphdef.RegisteredGradientKt.Dsl.() -> kotlin.Unit): graphdef.RegisteredGradient =
  graphdef.RegisteredGradientKt.Dsl._create(graphdef.RegisteredGradient.newBuilder()).apply { block() }._build()
public object RegisteredGradientKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: graphdef.RegisteredGradient.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: graphdef.RegisteredGradient.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): graphdef.RegisteredGradient = _builder.build()

    /**
     * <pre>
     * The gradient function's name.
     * </pre>
     *
     * <code>string gradient_func = 1;</code>
     */
    public var gradientFunc: kotlin.String
      @JvmName("getGradientFunc")
      get() = _builder.getGradientFunc()
      @JvmName("setGradientFunc")
      set(value) {
        _builder.setGradientFunc(value)
      }
    /**
     * <pre>
     * The gradient function's name.
     * </pre>
     *
     * <code>string gradient_func = 1;</code>
     */
    public fun clearGradientFunc() {
      _builder.clearGradientFunc()
    }

    /**
     * <pre>
     * The gradient function's registered op type.
     * </pre>
     *
     * <code>string registered_op_type = 2;</code>
     */
    public var registeredOpType: kotlin.String
      @JvmName("getRegisteredOpType")
      get() = _builder.getRegisteredOpType()
      @JvmName("setRegisteredOpType")
      set(value) {
        _builder.setRegisteredOpType(value)
      }
    /**
     * <pre>
     * The gradient function's registered op type.
     * </pre>
     *
     * <code>string registered_op_type = 2;</code>
     */
    public fun clearRegisteredOpType() {
      _builder.clearRegisteredOpType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun graphdef.RegisteredGradient.copy(block: graphdef.RegisteredGradientKt.Dsl.() -> kotlin.Unit): graphdef.RegisteredGradient =
  graphdef.RegisteredGradientKt.Dsl._create(this.toBuilder()).apply { block() }._build()

