// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: graphdef/tensor_shape.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package graphdef;

@kotlin.jvm.JvmName("-initializetensorShapeProto")
public inline fun tensorShapeProto(block: graphdef.TensorShapeProtoKt.Dsl.() -> kotlin.Unit): graphdef.TensorShapeProto =
  graphdef.TensorShapeProtoKt.Dsl._create(graphdef.TensorShapeProto.newBuilder()).apply { block() }._build()
/**
 * ```
 * Dimensions of a tensor.
 * ```
 *
 * Protobuf type `uni_model_proto.TensorShapeProto`
 */
public object TensorShapeProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: graphdef.TensorShapeProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: graphdef.TensorShapeProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): graphdef.TensorShapeProto = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DimProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" > 0, "unknown_rank" must be false.
     * ```
     *
     * `repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;`
     */
     public val dim: com.google.protobuf.kotlin.DslList<graphdef.TensorShapeProto.Dim, DimProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDimList()
      )
    /**
     * ```
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" > 0, "unknown_rank" must be false.
     * ```
     *
     * `repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;`
     * @param value The dim to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDim")
    public fun com.google.protobuf.kotlin.DslList<graphdef.TensorShapeProto.Dim, DimProxy>.add(value: graphdef.TensorShapeProto.Dim) {
      _builder.addDim(value)
    }
    /**
     * ```
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" > 0, "unknown_rank" must be false.
     * ```
     *
     * `repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;`
     * @param value The dim to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDim")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.TensorShapeProto.Dim, DimProxy>.plusAssign(value: graphdef.TensorShapeProto.Dim) {
      add(value)
    }
    /**
     * ```
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" > 0, "unknown_rank" must be false.
     * ```
     *
     * `repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;`
     * @param values The dim to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDim")
    public fun com.google.protobuf.kotlin.DslList<graphdef.TensorShapeProto.Dim, DimProxy>.addAll(values: kotlin.collections.Iterable<graphdef.TensorShapeProto.Dim>) {
      _builder.addAllDim(values)
    }
    /**
     * ```
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" > 0, "unknown_rank" must be false.
     * ```
     *
     * `repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;`
     * @param values The dim to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDim")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.TensorShapeProto.Dim, DimProxy>.plusAssign(values: kotlin.collections.Iterable<graphdef.TensorShapeProto.Dim>) {
      addAll(values)
    }
    /**
     * ```
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" > 0, "unknown_rank" must be false.
     * ```
     *
     * `repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;`
     * @param index The index to set the value at.
     * @param value The dim to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDim")
    public operator fun com.google.protobuf.kotlin.DslList<graphdef.TensorShapeProto.Dim, DimProxy>.set(index: kotlin.Int, value: graphdef.TensorShapeProto.Dim) {
      _builder.setDim(index, value)
    }
    /**
     * ```
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     *
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     *
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     *
     * If "dim.size()" > 0, "unknown_rank" must be false.
     * ```
     *
     * `repeated .uni_model_proto.TensorShapeProto.Dim dim = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDim")
    public fun com.google.protobuf.kotlin.DslList<graphdef.TensorShapeProto.Dim, DimProxy>.clear() {
      _builder.clearDim()
    }


    /**
     * ```
     * If true, the number of dimensions in the shape is unknown.
     *
     * If true, "dim.size()" must be 0.
     * ```
     *
     * `bool unknown_rank = 3;`
     */
    public var unknownRank: kotlin.Boolean
      @JvmName("getUnknownRank")
      get() = _builder.getUnknownRank()
      @JvmName("setUnknownRank")
      set(value) {
        _builder.setUnknownRank(value)
      }
    /**
     * ```
     * If true, the number of dimensions in the shape is unknown.
     *
     * If true, "dim.size()" must be 0.
     * ```
     *
     * `bool unknown_rank = 3;`
     */
    public fun clearUnknownRank() {
      _builder.clearUnknownRank()
    }
  }
  @kotlin.jvm.JvmName("-initializedim")
  public inline fun dim(block: graphdef.TensorShapeProtoKt.DimKt.Dsl.() -> kotlin.Unit): graphdef.TensorShapeProto.Dim =
    graphdef.TensorShapeProtoKt.DimKt.Dsl._create(graphdef.TensorShapeProto.Dim.newBuilder()).apply { block() }._build()
  /**
   * ```
   * One dimension of the tensor.
   * ```
   *
   * Protobuf type `uni_model_proto.TensorShapeProto.Dim`
   */
  public object DimKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: graphdef.TensorShapeProto.Dim.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: graphdef.TensorShapeProto.Dim.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): graphdef.TensorShapeProto.Dim = _builder.build()

      /**
       * ```
       * Size of the tensor in that dimension.
       * This value must be >= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * ```
       *
       * `int64 size = 1;`
       */
      public var size: kotlin.Long
        @JvmName("getSize")
        get() = _builder.getSize()
        @JvmName("setSize")
        set(value) {
          _builder.setSize(value)
        }
      /**
       * ```
       * Size of the tensor in that dimension.
       * This value must be >= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * ```
       *
       * `int64 size = 1;`
       */
      public fun clearSize() {
        _builder.clearSize()
      }

      /**
       * ```
       * Optional name of the tensor dimension.
       * ```
       *
       * `string name = 2;`
       */
      public var name: kotlin.String
        @JvmName("getName")
        get() = _builder.getName()
        @JvmName("setName")
        set(value) {
          _builder.setName(value)
        }
      /**
       * ```
       * Optional name of the tensor dimension.
       * ```
       *
       * `string name = 2;`
       */
      public fun clearName() {
        _builder.clearName()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun graphdef.TensorShapeProto.copy(block: `graphdef`.TensorShapeProtoKt.Dsl.() -> kotlin.Unit): graphdef.TensorShapeProto =
  `graphdef`.TensorShapeProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun graphdef.TensorShapeProto.Dim.copy(block: `graphdef`.TensorShapeProtoKt.DimKt.Dsl.() -> kotlin.Unit): graphdef.TensorShapeProto.Dim =
  `graphdef`.TensorShapeProtoKt.DimKt.Dsl._create(this.toBuilder()).apply { block() }._build()

