// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: graphdef/tensor.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package graphdef;

@kotlin.jvm.JvmName("-initializevariantTensorDataProto")
public inline fun variantTensorDataProto(block: graphdef.VariantTensorDataProtoKt.Dsl.() -> kotlin.Unit): graphdef.VariantTensorDataProto =
  graphdef.VariantTensorDataProtoKt.Dsl._create(graphdef.VariantTensorDataProto.newBuilder()).apply { block() }._build()
/**
 * ```
 * Protocol buffer representing the serialization format of DT_VARIANT tensors.
 * ```
 *
 * Protobuf type `uni_model_proto.VariantTensorDataProto`
 */
public object VariantTensorDataProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: graphdef.VariantTensorDataProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: graphdef.VariantTensorDataProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): graphdef.VariantTensorDataProto = _builder.build()

    /**
     * ```
     * Name of the type of objects being serialized.
     * ```
     *
     * `string type_name = 1;`
     */
    public var typeName: kotlin.String
      @JvmName("getTypeName")
      get() = _builder.getTypeName()
      @JvmName("setTypeName")
      set(value) {
        _builder.setTypeName(value)
      }
    /**
     * ```
     * Name of the type of objects being serialized.
     * ```
     *
     * `string type_name = 1;`
     */
    public fun clearTypeName() {
      _builder.clearTypeName()
    }

    /**
     * ```
     * Portions of the object that are not Tensors.
     * ```
     *
     * `bytes metadata = 2;`
     */
    public var metadata: com.google.protobuf.ByteString
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * ```
     * Portions of the object that are not Tensors.
     * ```
     *
     * `bytes metadata = 2;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TensorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Tensors contained within objects being serialized.
     * ```
     *
     * `repeated .uni_model_proto.TensorProto tensors = 3;`
     */
     public val tensors: com.google.protobuf.kotlin.DslList<graphdef.TensorProto, TensorsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTensorsList()
      )
    /**
     * ```
     * Tensors contained within objects being serialized.
     * ```
     *
     * `repeated .uni_model_proto.TensorProto tensors = 3;`
     * @param value The tensors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTensors")
    public fun com.google.protobuf.kotlin.DslList<graphdef.TensorProto, TensorsProxy>.add(value: graphdef.TensorProto) {
      _builder.addTensors(value)
    }
    /**
     * ```
     * Tensors contained within objects being serialized.
     * ```
     *
     * `repeated .uni_model_proto.TensorProto tensors = 3;`
     * @param value The tensors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTensors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.TensorProto, TensorsProxy>.plusAssign(value: graphdef.TensorProto) {
      add(value)
    }
    /**
     * ```
     * Tensors contained within objects being serialized.
     * ```
     *
     * `repeated .uni_model_proto.TensorProto tensors = 3;`
     * @param values The tensors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTensors")
    public fun com.google.protobuf.kotlin.DslList<graphdef.TensorProto, TensorsProxy>.addAll(values: kotlin.collections.Iterable<graphdef.TensorProto>) {
      _builder.addAllTensors(values)
    }
    /**
     * ```
     * Tensors contained within objects being serialized.
     * ```
     *
     * `repeated .uni_model_proto.TensorProto tensors = 3;`
     * @param values The tensors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTensors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<graphdef.TensorProto, TensorsProxy>.plusAssign(values: kotlin.collections.Iterable<graphdef.TensorProto>) {
      addAll(values)
    }
    /**
     * ```
     * Tensors contained within objects being serialized.
     * ```
     *
     * `repeated .uni_model_proto.TensorProto tensors = 3;`
     * @param index The index to set the value at.
     * @param value The tensors to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTensors")
    public operator fun com.google.protobuf.kotlin.DslList<graphdef.TensorProto, TensorsProxy>.set(index: kotlin.Int, value: graphdef.TensorProto) {
      _builder.setTensors(index, value)
    }
    /**
     * ```
     * Tensors contained within objects being serialized.
     * ```
     *
     * `repeated .uni_model_proto.TensorProto tensors = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTensors")
    public fun com.google.protobuf.kotlin.DslList<graphdef.TensorProto, TensorsProxy>.clear() {
      _builder.clearTensors()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun graphdef.VariantTensorDataProto.copy(block: `graphdef`.VariantTensorDataProtoKt.Dsl.() -> kotlin.Unit): graphdef.VariantTensorDataProto =
  `graphdef`.VariantTensorDataProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

